# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "photos", :force => true do |t|
    t.column "parent_id",    :integer
    t.column "user_id",      :integer
    t.column "content_type", :string
    t.column "filename",     :string
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "roles", :force => true do |t|
    t.column "title", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer
    t.column "user_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "last_login_at",             :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "visits_count",              :integer,                :default => 0
    t.column "time_zone",                 :string,                 :default => "Etc/UTC"
    t.column "photo_id",                  :integer
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
  end

end
